### ISSUE TITLE
Package doesn't serialize bookmarks amongs other things

### ISSUE THREAD

**Issue by Trudko** [danielmahon/atom-open-last-project#12]
Hi, 
I am using your package, thank you for creating it! :)
Problem is that bookmarks aren't serialized when closing the Atom, so when I reopen it, they got lost. It is because your package doesn't serialize.

I first opened issue in [bookmark package](https://github.com/atom/bookmarks/issues/22), you can find all the info here.

**Comment by danielmahon** [comment]
@Trudko Im closing this as they plan on adding this feature into core:
https://github.com/atom/atom/issues/1603
