### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ricardograca** [danielmahon/atom-open-last-project#15]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
Object.loadProject (/home/ricardo/.atom/packages/open-last-project/lib/open-last-project.js:72:13)
```

**Comment by steelbrain** [comment]
Duplicate of #13
