### ISSUE TITLE
Coffeescript, Maybe?

### ISSUE THREAD

**Issue by steelbrain** [danielmahon/atom-open-last-project#20]
The source is in javascript and javascript has some extra brackets and stuff that is not necessarily needed.
I think we should convert this to CoffeeScript. What is your opinion?

**Comment by danielmahon** [comment]
While I don't really have a problem with coffee-script, Id rather not take up converting it right now. Most likely the functionality of this package will be in the 1.0 release anyhow and I have little coffee-script experience so the syntax would be a learning curve. If you'd like to take a stab at it, be my guest, but not sure it's worth it.

On a side note, i'm still trying to get serialization working, any thoughts on #21?

**Comment by danielmahon** [comment]
@steelbrain Hey. Sorry for being MIA lately. I will take a look over things tonight and merge. Thanks for all your work!
