### ISSUE TITLE
Drop LocalStorage in favor of Serialization

### ISSUE THREAD

**Issue by danielmahon** [danielmahon/atom-open-last-project#21]
Id like to utilize the built in serialization for atom.io packages but can't seem to figure out how to get the state back after app restart. It works fine after reload, not restart. Im either missing something simple or it's by design. Most of what's needed is already in master, just not hooked up. Id appreciate any help on this. Im not too familiar with coffee-script so I take what I can from the docs.

**Comment by steelbrain** [comment]
I think this issue is a won't fix. Since It's serialization is per-project and without `open-last-project` Atom doesn't know what the project it. 
LocalStorage is a good thing, I don't find anything bad about it.

**Comment by steelbrain** [comment]
I think I made a mistake is understanding what you meant, Maybe you mean that we should store the ActiveProject's path in LocalStorage and each Project's opened files in Atom's Serialization Storage.
If that's the case, I think it'd be pretty useful. I'll try to implement it in the pull request.

**Comment by steelbrain** [comment]
Okay, so we have a new problem. Atom's serialization only gives us the state when atom is opened with that directory as an argument, `atom.project.setPaths` doesn't work with it.

**Comment by danielmahon** [comment]
@steelbrain yea i noticed that, going to try and add the files paths back into local storage
