### ISSUE TITLE
Ver 2.2 Not Working / Not installed in Ubuntu 14.04

### ISSUE THREAD

**Issue by rhoconlinux** [danielmahon/atom-open-last-project#23]
Hi! Here is the log I have. Probably there are some new dependencies? or it is just a permissions problem?

<pre>
npm ERR! addLocal Could not install /tmp/d-115112-13587-116b71h/package.tgz
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/opt/atom/resources/app/apm/.apmrc" "--userconfig" "/home/rho/.atom/.apmrc" "install" "/tmp/d-115112-13587-116b71h/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! path /var/lib/jenkins
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/var/lib/jenkins'
npm ERR!  { [Error: EACCES, mkdir '/var/lib/jenkins'] errno: 3, code: 'EACCES', path: '/var/lib/jenkins' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115112-13587-i9z3iv/npm-debug.log
</pre>

Thanks! Great Work! :D

**Comment by steelbrain** [comment]
@rhoconlinux I think it is a bug in atom v0.178.0
Can you please confirm that your atom version is different?
If you're running that version, Can you please upgrade your Atom and try again.

**Comment by rhoconlinux** [comment]
Sorry!
Solved with a dist-upgrade!!! :dart: 
Thank you very much. :+1:
