### ISSUE TITLE
Installing Open Last Project causes Atom's Tree View to not display the correct path to the project in Windows

### ISSUE THREAD

**Issue by scott-wilson** [danielmahon/atom-open-last-project#24]
Installing the Open Last Project package causes the tree view (as of 0.180) to display the root of Atom's install instead of the actual project in Windows. This causes Atom to always show the incorrect project after, and I have to uninstall/ reinstall Atom, and delete the user config to fix it.

**Comment by SethG911** [comment]
I am having the same issues.

**Comment by SethG911** [comment]
I am still having this issue with Atom 0.181.0 and Open-Last-Project 0.3.1.

**Comment by steelbrain** [comment]
@SethG911 I think It's an issue with Atom v0.180+
Can you please confirm this behavior on Atom v0.179
