### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sparkjames** [danielmahon/atom-open-last-project#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [open-last-project](https://github.com/danielmahon/atom-open-last-project) package, v0.3.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:167

TypeError: undefined is not a function
  at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:167:7)
  at Workspace.module.exports.Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:292:33)
  at /Users/sparkjames/.atom/packages/open-last-project/lib/main.coffee:13:42

```

### Commands

```
     -0:55.8 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dreamweaver-dark.theme-atom-dark-ui)
     -0:23.7 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dreamweaver-dark.theme-atom-dark-ui)
     -0:16.7 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dreamweaver-dark.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "dreamweaver-dark"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "wrap-guide",
      "project-manager"
    ],
    "projectHome": "/Applications/MAMP/htdocs"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
compare-files, v0.4.1
dreamweaver-dark, v0.1.0
javascript-snippets, v1.0.0
open-last-project, v0.3.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by sparkjames** [comment]
I don't know if this is helpful or not, but Atom suggested I post that :P

**Comment by angelhvargas** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [open-last-project](https://github.com/danielmahon/atom-open-last-project) package, v0.3.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Angel\AppData\Local\atom\app-0.182.0\resources\app\src\pane-container.js:167

TypeError: undefined is not a function
  at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (C:\Users\Angel\AppData\Local\atom\app-0.182.0\resources\app\src\pane-container.js:167:7)
  at Workspace.module.exports.Workspace.observeActivePaneItem (C:\Users\Angel\AppData\Local\atom\app-0.182.0\resources\app\src\workspace.js:290:33)
  at C:\Users\Angel\.atom\packages\open-last-project\lib\main.coffee:13:42

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
autoclose-html, v0.15.0
css-color-underline, v1.0.1
language-blade, v0.7.0
laravel, v0.4.2
laravel-facades, v1.0.0
monokai, v0.12.0
open-last-project, v0.3.2
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by danielmahon** [comment]
is there a specifric time when this is happening, I cannot reproduce it

**Comment by danielmahon** [comment]
I think this should fix it, i still havent been able to reproduce the issue though

**Comment by sparkjames** [comment]
It happened when I tried to update the plugin. I had to delete the plugin
folder via Finder and reinstall the plugin through Atom to get it to work.

__________________________












* James Pfleiderer Senior Front-end Developer (d) 301.358.0310(o)
301.294.3340james@sparkexperience.com <james@sparkexperience.com>
www.sparkexperience.com <http://www.sparkexperience.com> We are a green
certified business — please consider the environment before printing this
email. *

**Comment by danielmahon** [comment]
try installing the latest version 0.3.4 and let me know if it still happens

**Comment by sparkjames** [comment]
Just installed the update through the settings pane and it worked fine!

__________________________












* James Pfleiderer Senior Front-end Developer (d) 301.358.0310(o)
301.294.3340james@sparkexperience.com <james@sparkexperience.com>
www.sparkexperience.com <http://www.sparkexperience.com> We are a green
certified business — please consider the environment before printing this
email. *

**Comment by angelhvargas** [comment]
Thanks guys...
