### ISSUE TITLE
Package no longer works

### ISSUE THREAD

**Issue by prabackar** [danielmahon/atom-open-last-project#31]
After recent update  atom@0.181.0, every time I quit and open atom, it open a untitled file and ignores previously opened folder.

**Comment by danielmahon** [comment]
@prabackar have you updated to version 0.3.4?

**Comment by prabackar** [comment]
yep

**Comment by danielmahon** [comment]
what's your environment? any errors in the atom console? from other packages as well? im running 0.184.0 with no problems on OSX

**Comment by prabackar** [comment]
OSX 10.10.2 / atom 0.184.0

Just warnings
![screen shot 2015-02-26 at 4 09 59 pm](https://cloud.githubusercontent.com/assets/931394/6404901/f704a96c-bdd1-11e4-80d8-6de473733882.png)

**Comment by danielmahon** [comment]
@prabackar still having a problem?

**Comment by prabackar** [comment]
After the recent atom update, the issue got fixed!! Now it is working fine. Thank you!
