### ISSUE TITLE
why you use coffee rather than js?

### ISSUE THREAD

**Issue by chapgaga** [danielmahon/atom-open-last-project#43]
can atom use coffee directly, or atom will compile it into js when this plugin is installed?

**Comment by danielmahon** [comment]
@chapgaga Not sure. I assume it doesnt compile as the package's folders remain clean. As to why: coffeescript is the "standard" Atom.io package format. I initially created this package in JS but after @steelbrain offered up a rewrite I decided to go with it and also gave me an excuse to mess with coffeescript.

**Comment by steelbrain** [comment]
@chapgaga Atom uses coffeescript directly, It transpiles the files first time and uses transpiled vanilla JS files afterwards.

and Not only coffeescript, it supports TypeScript and ES6 as well.
