### ISSUE TITLE
Does not work in Archlinux

### ISSUE THREAD

**Issue by gutenye** [danielmahon/atom-open-last-project#45]
I did a little dig, open `$ atom` in terminal will always contain current directory path in `atom.project.getPaths()` method, whick makes https://github.com/danielmahon/atom-open-last-project/blob/master/lib/main.coffee#L8 never executed.

It appears `$ atom` is same as `$atom .` in Archlinux, any ideas why?

```
$ atom --version
0.190.0
```

**Comment by gutenye** [comment]
Further more, the problem appears `--executed-from="$(pwd)"` in https://github.com/atom/atom/blob/master/atom.sh#L87)

**Comment by danielmahon** [comment]
Project is deprecated #44
