### ISSUE TITLE
remember split panes

### ISSUE THREAD

**Issue by tedyun** [danielmahon/atom-open-last-project#6]
It seems the plugin doesn't respect split panes when it opens the last project and files. Is there any plan to support this feature?

Thank you for an awesome plugin.

**Comment by yamsellem** [comment]
+1 ;-)

**Comment by danielmahon** [comment]
Looks like core will end up supporting this for 1.0
https://github.com/atom/atom/issues/1603

I might still implement this depending on the timeline

**Comment by pitaj** [comment]
:+1:

**Comment by asiahoe** [comment]
What's really odd is, before the recent updates to Atom (< 0.187.0) and your package (0.3.4), I was able to retrieve split panes by closing the window and reopening the project. Recent changes have removed this functionality. :(

**Comment by danielmahon** [comment]
I think it has to do with Atom's plethora of changes lately, some of which aren't so stable. Im currently working (albeit slowly) on fixes for multi windows/panes/root folders.

**Comment by danielmahon** [comment]
Project is deprecated #44
